// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA2nUBffXCluIyqE53AAHB8Zq6ROCWDi0',
    appId: '1:848704323803:web:94663bf996f6fd02950cfe',
    messagingSenderId: '848704323803',
    projectId: 'dsi--project',
    authDomain: 'dsi--project.firebaseapp.com',
    storageBucket: 'dsi--project.appspot.com',
    measurementId: 'G-CZ107BSC2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVE7H6YKzvmzbVdZa_BHFz7tegMXoj174',
    appId: '1:848704323803:android:2fda0308f7568e54950cfe',
    messagingSenderId: '848704323803',
    projectId: 'dsi--project',
    storageBucket: 'dsi--project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAChkYiqhqVmNc9FVaLRo9tMXTsDonYpAU',
    appId: '1:848704323803:ios:3a0efeec47bf1988950cfe',
    messagingSenderId: '848704323803',
    projectId: 'dsi--project',
    storageBucket: 'dsi--project.appspot.com',
    iosClientId: '848704323803-rsquigct1bpigerqj0qt2s0gdqpc7nfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.startUpNamer',
  );
}
